name = "aks-astro-template"
type = "javascript" # or "webpack" or "rust"

# Define your account and project details
account_id = "781f2601c68594125b6b97567364d0d6"
workers_dev = true # Set to false if deploying to a custom domain or production
compatibility_date = "2024-08-09" # Today's date or the date when the project was last updated

[vars]
PUBLIC_LOCALES="nb,en"
PUBLIC_OTHER_LOCALES="en"
PUBLIC_DEFAULT_LOCALE="nb"
PUBLIC_META_LOCALES="nb_NO,en_US"

PUBLIC_SITE_URL="https://aks-astro-template.pages.dev"
PUBLIC_GITHUB_REPO="https://github.com/aksellsor/aks_astro_template"
PUBLIC_UMBRACO_URL="https://1251167-www.web.tornado-node.net/umbraco"
PUBLIC_CLOUDFLARE_DASH="https://dash.cloudflare.com/781f2601c68594125b6b97567364d0d6/pages/view/aks-astro-template"

IMAGE_CDN="https://1251167-www.web.tornado-node.net"
UMBRACO_ROOT_NODE="a6244e26-7dd6-4bf6-9052-d276e3ed827c"
UMBRACO_PREVIEW_API_KEY=""